name: Build Geode Mod

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install Geode CLI
      run: |
        pip install git+https://github.com/geode-sdk/cli.git

    - name: Install Geode SDK
      run: |
        geode sdk install

    - name: Build Mod
      run: |
        geode build

    - name: Upload .geode
      uses: actions/upload-artifact@v3
      with:
        name: decorgpt
        path: build/*.geode
